---
- name: Po10-30
  hosts: N93180_ACCESO
  gather_facts: no
  connection: ansible.netcommon.network_cli  
  
  
  tasks:
    - name: Po10-30  
      cisco.nxos.nxos_command:
        src: "{{ playbook_dir }}/Po10-30.txt"

      register: QoS

    - name: ImprimirConfig
      debug: var=QoS
