---
- name: VideoContribucion
  hosts: N93180_ACCESO
  gather_facts: no
  connection: ansible.netcommon.network_cli  
  
  
  tasks:
    - name: VideoContribucion  
      cisco.nxos.nxos_command:
        src: "{{ playbook_dir }}/VideoContribucion.txt"

      register: QoS

    - name: ImprimirConfig
      debug: var=QoS
